name: Website - Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/main
          fetch-depth: 1
          
      - uses: actions/setup-node@v1
        with:
          node-version: '14.15.1'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build production APP
        run: npm run build:prd
        
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gsutil -m rsync -d -c -r /dist/spa gs://adata.games